/**
 * Just enough XML reading for two machine-generated feeds: arXiv's Atom and PubMed's article set.
 *
 * Targeted extraction of known elements, the approach `extract/docx-comments.ts` already takes
 * for Word's XML — not a general parser. Both feeds are well-formed, generated by the services
 * themselves, and read for a handful of named fields; a dependency for that would be heavier
 * than the problem. Neither format nests an element inside another of the same name for the
 * fields read here.
 */

const NAMED_ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
};

/** `&amp;`, `&#233;`, `&#x3B1;` → their characters. An entity it does not know is left as it is. */
export function decodeXml(text: string): string {
  return text.replace(/&(#x[0-9a-f]+|#[0-9]+|[a-z]+);/gi, (whole, code: string) => {
    if (code.startsWith('#')) {
      const hex = code[1] === 'x' || code[1] === 'X';
      const n = Number.parseInt(code.slice(hex ? 2 : 1), hex ? 16 : 10);
      return Number.isInteger(n) && n > 0 && n <= 0x10ffff ? String.fromCodePoint(n) : whole;
    }
    return NAMED_ENTITIES[code.toLowerCase()] ?? whole;
  });
}

const escapeName = (tag: string): string => tag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Every `<tag …>…</tag>` in document order, with its attribute text and its inner XML. */
export function elements(xml: string, tag: string): Array<{ attrs: string; inner: string }> {
  const name = escapeName(tag);
  const re = new RegExp(`<${name}(\\s[^>]*)?>([\\s\\S]*?)</${name}>`, 'g');
  const out: Array<{ attrs: string; inner: string }> = [];
  for (const match of xml.matchAll(re)) out.push({ attrs: match[1] ?? '', inner: match[2] ?? '' });
  return out;
}

/** The inner XML of the first `<tag>`, or null when there is none. */
export function firstInner(xml: string, tag: string): string | null {
  return elements(xml, tag)[0]?.inner ?? null;
}

/** One attribute's value from an element's attribute text, decoded. */
export function attribute(attrs: string, name: string): string | null {
  const match = new RegExp(`\\s${escapeName(name)}="([^"]*)"`).exec(attrs);
  return match ? decodeXml(match[1] ?? '') : null;
}

/**
 * Inner XML → plain text. CDATA is unwrapped, inline markup (`<i>`, `<sup>`) is dropped but its
 * text kept, entities are decoded, and runs of whitespace — the feeds wrap long titles across
 * lines — become one space.
 */
export function plainText(inner: string | null | undefined): string {
  if (!inner) return '';
  return decodeXml(inner.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1').replace(/<[^>]+>/g, ''))
    .replace(/\s+/g, ' ')
    .trim();
}
