/**
 * Discipline profiles — ADR-0039, the specification's §4.2 "discipline families (initial set)".
 *
 * Citation styles are the common defaults only; the university profile always overrides them.
 * Terminology rules are a starting sheet: the student's own glossary is merged in at build time
 * and wins on conflict, because the student owns the thesis (A.0 rule 5).
 */

import type { DisciplineProfile, EntityType } from './types.js';

const t = (code: string, label: string, hint: string): EntityType => ({ code, label, hint });

/** Notation every discipline uses that must not be read as an undefined abbreviation (check L3). */
const COMMON_KNOWN = [
  'PhD',
  'MPhil',
  'MSc',
  'MTech',
  'MBA',
  'MA',
  'LLM',
  'MD',
  'MPharm',
  'USA',
  'UK',
  'EU',
  'UN',
  'WHO',
  'ISO',
  'SI',
  'DOI',
  'URL',
  'PDF',
  'ID',
  'IT',
  'AI',
  'CO2',
  'pH',
  'DNA',
  'RNA',
  'GDP',
  'NGO',
  'IEEE',
  'APA',
  'MLA',
  'OK',
  'AD',
  'BC',
  'CE',
  'BCE',
  'AM',
  'PM',
  'et',
  'al',
];

export const DISCIPLINE_PROFILES: readonly DisciplineProfile[] = [
  {
    id: 'engineering_core_v1',
    displayName: 'Engineering (core)',
    departments: [
      'Mechanical',
      'Civil',
      'Materials',
      'Production',
      'Chemical',
      'Aerospace',
      'Automobile',
      'Metallurgy',
    ],
    defaultParadigms: ['experimental', 'computational'],
    entityTypes: [
      t(
        'MATERIAL',
        'Material',
        'an alloy, composite, polymer, ceramic, reinforcement or grade, e.g. AA7050, Ti3Al, graphite',
      ),
      t(
        'PROCESS',
        'Process',
        'a manufacturing or treatment process, e.g. stir casting, wire EDM, heat treatment',
      ),
      t(
        'PARAMETER',
        'Process parameter',
        'a variable that is set or varied, e.g. pulse-on time, feed rate, sintering temperature',
      ),
      t(
        'TEST',
        'Test or characterisation',
        'a test or measurement, e.g. pin-on-disc wear test, SEM, tensile test, SSCC test',
      ),
      t(
        'MODEL',
        'Model or method',
        'an analytical, statistical or numerical method, e.g. Taguchi, RSM, finite element model, ANN',
      ),
      t('STANDARD', 'Standard', 'a named test or product standard, e.g. ASTM G99, IS 1608'),
      t(
        'APPLICATION',
        'Application',
        'the intended use or industry, e.g. aerospace structures, brake discs',
      ),
    ],
    defaultCitationStyle: 'apa',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 10, share: 0.4 },
    evidenceSources: ['OpenAlex', 'Crossref', 'Semantic Scholar', 'arXiv'],
    specialChecks: ['D-ENG1', 'D-ENG2', 'D-ENG3', 'D-ENG4'],
    terminology: [
      {
        preferred: 'electrical discharge machining',
        avoid: [
          'electric discharge machining',
          'electro discharge machining',
          'electro-discharge machining',
        ],
      },
      { preferred: 'wire EDM', avoid: ['wire-cut EDM', 'wire cut EDM', 'wirecut EDM'] },
      {
        preferred: 'aluminium matrix composite',
        avoid: ['aluminum matrix composite', 'Al matrix composite'],
      },
      {
        preferred: 'stress corrosion cracking',
        avoid: ['stress-corrosion cracking', 'stress corrosion crack'],
      },
      { preferred: 'statically loaded', avoid: ['statistically loaded'] },
      { preferred: 'microstructure', avoid: ['micro structure', 'micro-structure'] },
      { preferred: 'wear rate', avoid: ['wear-rate', 'rate of wear'] },
    ],
    examinerFocus: [
      'a property value outside the range known for that material (hardness, density, melting point, strength)',
      'a process described with steps that belong to a different process (powder metallurgy with melting; squeeze casting with stirring)',
      'a chemical formula or flux that is not a real compound, or an equation that does not balance',
      'a unit that does not fit its quantity, or a non-SI unit without conversion',
      'a finding about one alloy or reinforcement applied to another as if it held',
    ],
    requiresTheoreticalFramework: false,
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'EDM',
      'WEDM',
      'SEM',
      'EDS',
      'XRD',
      'TEM',
      'ASTM',
      'IS',
      'BS',
      'CNC',
      'FEM',
      'FEA',
      'CAD',
      'CAM',
      'RSM',
      'ANOVA',
      'ANN',
      'HV',
      'HRC',
      'HB',
      'MPa',
      'GPa',
      'kN',
      'rpm',
      'UTS',
      'YS',
      'CTE',
    ],
  },
  {
    id: 'electrical_cs_v1',
    displayName: 'Electrical, Electronics, Computer Science and IT',
    departments: ['EEE', 'ECE', 'CSE', 'IT', 'AI and Data Science', 'Instrumentation'],
    defaultParadigms: ['design_build', 'computational', 'experimental'],
    entityTypes: [
      t(
        'ALGORITHM',
        'Algorithm or model',
        'a named algorithm, learning model or technique, e.g. YOLOv8, random forest, Kalman filter',
      ),
      t(
        'ARCHITECTURE',
        'Architecture or system',
        'a system, circuit, network or hardware architecture, e.g. transformer encoder, buck converter',
      ),
      t(
        'DATASET',
        'Dataset',
        'a named dataset or data source, e.g. CIFAR-10, MIMIC-III, a field survey',
      ),
      t('METRIC', 'Metric', 'an evaluation measure, e.g. accuracy, F1, RMSE, latency, THD'),
      t('BASELINE', 'Baseline', 'a method the work is compared against'),
      t(
        'HARDWARE',
        'Hardware or platform',
        'a device, board, sensor or platform, e.g. Raspberry Pi 4, FPGA, LoRa',
      ),
      t(
        'PROTOCOL',
        'Protocol or standard',
        'a communication protocol or standard, e.g. MQTT, IEEE 802.15.4, 5G NR',
      ),
    ],
    defaultCitationStyle: 'ieee',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 5, share: 0.5 },
    evidenceSources: ['OpenAlex', 'arXiv', 'Semantic Scholar', 'Crossref'],
    specialChecks: ['D-CS1', 'D-ENG4'],
    terminology: [
      { preferred: 'machine learning', avoid: ['machine-learning'] },
      { preferred: 'deep learning', avoid: ['deep-learning'] },
      { preferred: 'dataset', avoid: ['data set', 'data-set'] },
      { preferred: 'hyperparameter', avoid: ['hyper-parameter', 'hyper parameter'] },
      { preferred: 'real time', avoid: ['realtime'] },
    ],
    examinerFocus: [
      'a metric used before it is defined, or a metric that does not fit the task',
      'a dataset described after results that depend on it, or never described',
      'a comparison with no named baseline, or a baseline compared under different conditions',
      'a claim of improvement with no figure, or a figure with no test conditions',
      'reproducibility: implementation environment, hyperparameters and splits stated',
    ],
    requiresTheoreticalFramework: false,
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'CPU',
      'GPU',
      'RAM',
      'API',
      'IoT',
      'ML',
      'DL',
      'CNN',
      'RNN',
      'LSTM',
      'SVM',
      'RMSE',
      'MAE',
      'MSE',
      'ROC',
      'AUC',
      'FPGA',
      'PCB',
      'ADC',
      'DAC',
      'PWM',
      'DC',
      'AC',
      'RF',
      'LED',
      'USB',
      'HTTP',
      'TCP',
      'IP',
      'SQL',
      'JSON',
      'XML',
      'OS',
      'Hz',
      'kHz',
      'MHz',
      'GHz',
      'ms',
      'dB',
    ],
  },
  {
    id: 'pure_sciences_v1',
    displayName: 'Pure sciences',
    departments: [
      'Physics',
      'Chemistry',
      'Biology',
      'Mathematics',
      'Statistics',
      'Biotechnology',
      'Microbiology',
    ],
    defaultParadigms: ['experimental', 'theoretical', 'computational'],
    entityTypes: [
      t(
        'PHENOMENON',
        'Phenomenon',
        'the effect or process studied, e.g. photocatalysis, gene silencing, turbulence',
      ),
      t(
        'COMPOUND',
        'Compound or material',
        'a chemical compound, catalyst or material, e.g. TiO2, graphene oxide, ZnO nanoparticles',
      ),
      t(
        'ORGANISM',
        'Organism or system',
        'a species, cell line, strain or physical system, e.g. E. coli, HeLa cells, a two-level atom',
      ),
      t(
        'TECHNIQUE',
        'Technique',
        'an experimental or analytical technique, e.g. XRD, HPLC, PCR, DFT',
      ),
      t('THEOREM', 'Theorem or model', 'a named theorem, law, equation or theoretical model'),
      t('MODEL', 'Model', 'a theoretical, statistical or computational model'),
    ],
    defaultCitationStyle: 'apa',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 10, share: 0.4 },
    evidenceSources: ['Crossref', 'OpenAlex', 'arXiv', 'PubMed'],
    specialChecks: ['D-ENG1', 'D-ENG2', 'D-ENG3', 'D-ENG4'],
    terminology: [
      { preferred: 'nanoparticles', avoid: ['nano particles', 'nano-particles'] },
      { preferred: 'X-ray diffraction', avoid: ['x-ray diffraction', 'XRD analysis method'] },
      { preferred: 'in vitro', avoid: ['in-vitro', 'invitro'] },
      { preferred: 'in vivo', avoid: ['in-vivo', 'invivo'] },
    ],
    examinerFocus: [
      'a formula, reaction or equation that is not valid or does not balance',
      'a theorem or law stated inaccurately or attributed wrongly',
      'a unit or order of magnitude that does not fit the quantity',
      'a mechanism asserted where only a correlation was shown',
    ],
    requiresTheoreticalFramework: false,
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'XRD',
      'SEM',
      'TEM',
      'FTIR',
      'UV',
      'HPLC',
      'PCR',
      'NMR',
      'DFT',
      'nm',
      'µm',
      'mM',
      'µM',
      'mL',
      'µL',
      'kDa',
      'ATP',
      'IUPAC',
    ],
  },
  {
    id: 'medicine_health_v1',
    displayName: 'Medicine, Nursing, Dental and Allied Health',
    departments: ['MD', 'MS', 'MDS', 'Nursing', 'Physiotherapy', 'Public Health', 'Allied Health'],
    defaultParadigms: ['clinical', 'quantitative', 'mixed', 'qualitative'],
    entityTypes: [
      t('CONDITION', 'Condition', 'the disease, disorder or health state studied'),
      t(
        'POPULATION',
        'Population',
        'who is studied: age group, setting, diagnosis, e.g. adults with type 2 diabetes in rural Tamil Nadu',
      ),
      t('INTERVENTION', 'Intervention', 'the treatment, programme, drug or exposure'),
      t(
        'COMPARATOR',
        'Comparator',
        'what the intervention is compared against: placebo, usual care, another treatment',
      ),
      t('OUTCOME', 'Outcome', 'what is measured, e.g. HbA1c, pain score, readmission'),
      t(
        'STUDY_DESIGN',
        'Study design',
        'e.g. randomised controlled trial, cohort, cross-sectional',
      ),
    ],
    defaultCitationStyle: 'vancouver',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 5, share: 0.5 },
    evidenceSources: ['PubMed', 'Crossref', 'OpenAlex', 'clinical guidelines the student uploads'],
    specialChecks: ['D-MED1', 'D-MED2', 'D-ENG4'],
    terminology: [
      {
        preferred: 'randomised controlled trial',
        avoid: ['randomized control trial', 'randomised control trial'],
      },
      {
        preferred: 'type 2 diabetes mellitus',
        avoid: ['type II diabetes', 'type-2 diabetes', 'diabetes type 2'],
      },
      { preferred: 'health care', avoid: ['healthcare'] },
    ],
    examinerFocus: [
      'a PICO element (population, intervention, comparator, outcome) missing or vague',
      'a dose, frequency or unit that is not plausible, or a drug name that is not real',
      'a guideline cited as current when it has been superseded',
      'a finding from one population applied to another (age, setting, severity) as if it held',
      'clinical advice beyond what the cited evidence supports; ethics approval and consent not stated',
    ],
    requiresTheoreticalFramework: false,
    sensitiveNote:
      'This is academic writing, not clinical advice. Treatment decisions belong to a qualified clinician.',
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'RCT',
      'BMI',
      'HbA1c',
      'BP',
      'CI',
      'OR',
      'RR',
      'HR',
      'SD',
      'mg',
      'kg',
      'mL',
      'mmHg',
      'ICU',
      'ICD',
      'ICMR',
      'IRB',
      'IEC',
      'PICO',
      'CONSORT',
      'PRISMA',
      'STROBE',
    ],
  },
  {
    id: 'pharmacy_v1',
    displayName: 'Pharmacy',
    departments: ['MPharm', 'PharmD', 'Pharmaceutics', 'Pharmacology', 'Pharmaceutical Chemistry'],
    defaultParadigms: ['experimental', 'clinical'],
    entityTypes: [
      t('DRUG', 'Drug or active ingredient', 'the compound or drug studied'),
      t(
        'FORMULATION',
        'Formulation',
        'dosage form or delivery system, e.g. nanoemulsion, sustained-release tablet',
      ),
      t('TARGET', 'Target or condition', 'the receptor, pathway, organism or condition addressed'),
      t('ASSAY', 'Assay or method', 'the test used, e.g. HPLC assay, dissolution test, MTT assay'),
      t('POPULATION', 'Population or model', 'patients, animals or cell lines studied'),
    ],
    defaultCitationStyle: 'vancouver',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 10, share: 0.4 },
    evidenceSources: ['PubMed', 'Crossref', 'OpenAlex'],
    specialChecks: ['D-MED2', 'D-ENG2', 'D-ENG4', 'D-MED1'],
    terminology: [
      {
        preferred: 'active pharmaceutical ingredient',
        avoid: ['active ingredient (API)', 'active pharma ingredient'],
      },
      { preferred: 'in vitro', avoid: ['in-vitro', 'invitro'] },
      { preferred: 'in vivo', avoid: ['in-vivo', 'invivo'] },
    ],
    examinerFocus: [
      'a dose or concentration with a unit that does not fit, or outside any plausible range',
      'a drug, excipient or reagent name that is not real or is misspelt',
      'a pharmacopoeia standard cited without edition, or a method claimed as official without a reference',
      'an animal or in-vitro result stated as if it held in patients',
    ],
    requiresTheoreticalFramework: false,
    sensitiveNote: 'This is academic writing, not clinical or dispensing advice.',
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'API',
      'HPLC',
      'UV',
      'FTIR',
      'DSC',
      'IP',
      'BP',
      'USP',
      'mg',
      'kg',
      'mL',
      'µg',
      'MTT',
      'IC50',
      'LD50',
      'CDSCO',
      'FDA',
    ],
  },
  {
    id: 'agriculture_environment_v1',
    displayName: 'Agriculture, Life and Environmental Sciences',
    departments: [
      'Agronomy',
      'Horticulture',
      'Soil Science',
      'Environmental Science',
      'Forestry',
      'Fisheries',
      'Food Science',
    ],
    defaultParadigms: ['experimental', 'quantitative'],
    entityTypes: [
      t(
        'CROP_SPECIES',
        'Crop or species',
        'the crop, variety, species or organism, e.g. rice ADT 43, Azolla',
      ),
      t(
        'TREATMENT',
        'Treatment',
        'what is applied or varied, e.g. biochar at 5 t/ha, drip irrigation',
      ),
      t('SITE', 'Site', 'where the work is done: farm, station, region, agro-climatic zone'),
      t('SEASON', 'Season or period', 'season, year or period, e.g. kharif 2024'),
      t(
        'METHOD',
        'Method or design',
        'the experimental design or analysis, e.g. RBD with three replications',
      ),
      t('INDICATOR', 'Indicator', 'what is measured, e.g. grain yield, soil organic carbon, BOD'),
    ],
    defaultCitationStyle: 'apa',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 10, share: 0.4 },
    evidenceSources: ['Crossref', 'OpenAlex', 'Semantic Scholar'],
    specialChecks: ['D-ENG4', 'D-ENG2'],
    terminology: [
      {
        preferred: 'randomised block design',
        avoid: ['randomized block design', 'random block design'],
      },
      {
        preferred: 'soil organic carbon',
        avoid: ['soil organic-carbon', 'organic carbon of soil'],
      },
    ],
    examinerFocus: [
      'a site or season not described, so the result cannot be placed',
      'a statistical design not named (RBD, CRD, split plot) or replication not stated',
      'a rate or yield with a unit that does not fit (kg/ha, t/ha, %)',
      'a finding from one agro-climatic zone or variety applied to another as if it held',
    ],
    requiresTheoreticalFramework: false,
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'RBD',
      'CRD',
      'FYM',
      'NPK',
      'ha',
      'kg',
      'BOD',
      'COD',
      'ICAR',
      'FAO',
      'GIS',
      'NDVI',
      'DAS',
      'DAT',
    ],
  },
  {
    id: 'management_commerce_v1',
    displayName: 'Management and Commerce',
    departments: [
      'MBA',
      'Commerce',
      'Finance',
      'HRM',
      'Marketing',
      'Operations',
      'Entrepreneurship',
    ],
    defaultParadigms: ['quantitative', 'mixed', 'qualitative'],
    entityTypes: [
      t(
        'CONSTRUCT',
        'Construct',
        'a concept measured indirectly, e.g. job satisfaction, brand trust',
      ),
      t('VARIABLE_IV', 'Independent variable', 'what is proposed to cause or predict'),
      t('VARIABLE_DV', 'Dependent variable', 'what is proposed to be affected'),
      t('MEDIATOR', 'Mediator', 'a variable through which an effect passes'),
      t('MODERATOR', 'Moderator', 'a variable that changes the strength of an effect'),
      t(
        'THEORY',
        'Theory',
        'a named theory or model, e.g. Technology Acceptance Model, resource-based view',
      ),
      t('POPULATION', 'Population', 'who is studied, e.g. MSME owners in Coimbatore'),
      t('SETTING', 'Setting', 'industry, sector or region'),
      t(
        'INSTRUMENT',
        'Instrument',
        'a questionnaire or scale, e.g. UWES-9, a 5-point Likert scale',
      ),
      t(
        'ANALYSIS_METHOD',
        'Analysis method',
        'e.g. structural equation modelling, multiple regression',
      ),
    ],
    defaultCitationStyle: 'apa',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 10, share: 0.4 },
    evidenceSources: ['OpenAlex', 'Crossref', 'Semantic Scholar'],
    specialChecks: ['D-MGT1', 'D-MGT2'],
    terminology: [
      {
        preferred: 'structural equation modelling',
        avoid: ['structural equation modeling', 'structured equation modelling'],
      },
      {
        preferred: 'small and medium enterprises',
        avoid: ['small and medium-sized enterprise', 'SMEs sector'],
      },
      { preferred: 'Likert scale', avoid: ['likert scale', 'Likert-type scale'] },
    ],
    examinerFocus: [
      'a hypothesis naming a variable that was not defined earlier, or with no direction stated',
      'a construct used before its definition, or two definitions for one construct',
      'a conceptual framework that does not match the hypotheses',
      'a correlation described as causation',
      'instrument reliability and validity not reported (Cronbach alpha, CFA, pilot)',
    ],
    requiresTheoreticalFramework: true,
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'SEM',
      'CFA',
      'EFA',
      'PLS',
      'SPSS',
      'AMOS',
      'TAM',
      'UTAUT',
      'SME',
      'MSME',
      'HR',
      'HRM',
      'CSR',
      'ROI',
      'KPI',
      'CEO',
      'B2B',
      'B2C',
    ],
  },
  {
    id: 'social_sciences_education_v1',
    displayName: 'Social Sciences, Education and Psychology',
    departments: [
      'Sociology',
      'Economics',
      'Education',
      'Psychology',
      'Social Work',
      'Political Science',
      'Public Administration',
    ],
    defaultParadigms: ['quantitative', 'qualitative', 'mixed'],
    entityTypes: [
      t(
        'CONSTRUCT',
        'Construct',
        'a concept measured or interpreted, e.g. self-efficacy, social capital',
      ),
      t(
        'THEORY',
        'Theory or framework',
        'a named theory, e.g. constructivism, human capital theory',
      ),
      t('POPULATION', 'Population or participants', 'who is studied'),
      t('SETTING', 'Setting', 'where: schools, districts, communities, institutions'),
      t('INSTRUMENT', 'Instrument', 'a scale, test, interview protocol or observation schedule'),
      t(
        'POLICY',
        'Policy or programme',
        'a named policy, scheme or programme, e.g. NEP 2020, MGNREGA',
      ),
    ],
    defaultCitationStyle: 'apa',
    genericBackgroundCap: 0.25,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 10, share: 0.4 },
    evidenceSources: ['OpenAlex', 'Crossref', 'Semantic Scholar', 'ERIC (education)'],
    specialChecks: ['D-MGT1', 'D-MGT2'],
    terminology: [
      {
        preferred: 'socio-economic status',
        avoid: ['socioeconomic status', 'socio economic status'],
      },
      { preferred: 'higher secondary', avoid: ['higher-secondary', 'senior secondary'] },
    ],
    examinerFocus: [
      'a theoretical framework named but never used to interpret anything',
      'sampling not described: who, how many, how chosen',
      'a correlation described as causation, or a sample generalised beyond its population',
      'ethics, consent and (in qualitative work) the researcher’s own position not addressed',
    ],
    requiresTheoreticalFramework: true,
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'SES',
      'NEP',
      'NCERT',
      'UGC',
      'SPSS',
      'ANOVA',
      'IQ',
      'GPA',
      'NGO',
      'SHG',
      'MGNREGA',
    ],
  },
  {
    id: 'law_v1',
    displayName: 'Law',
    departments: [
      'LLM',
      'PhD Law',
      'Constitutional Law',
      'Corporate Law',
      'Criminal Law',
      'International Law',
    ],
    defaultParadigms: ['doctrinal', 'quantitative', 'mixed'],
    entityTypes: [
      t(
        'STATUTE',
        'Statute or instrument',
        'an Act, code, regulation, treaty or constitutional provision, with year',
      ),
      t('CASE', 'Case', 'a decided case, with court and year'),
      t(
        'DOCTRINE',
        'Doctrine or principle',
        'a legal doctrine or principle, e.g. basic structure, proportionality',
      ),
      t(
        'JURISDICTION',
        'Jurisdiction',
        'the legal system(s) studied, e.g. India, England and Wales, EU',
      ),
      t('INSTITUTION', 'Institution', 'a court, tribunal, regulator or body'),
    ],
    defaultCitationStyle: 'oscola',
    genericBackgroundCap: 0.2,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 15, share: 0.3 },
    evidenceSources: ['statutes and cases the student uploads', 'Crossref (articles)', 'OpenAlex'],
    specialChecks: ['D-LAW1'],
    terminology: [
      { preferred: 'Supreme Court of India', avoid: ['Indian Supreme Court', 'SC of India'] },
      { preferred: 'High Court', avoid: ['high court'] },
    ],
    examinerFocus: [
      'a case or statute cited without a verifiable reference, or a case stated to hold what it does not',
      'a case that has been overruled or a provision that has been repealed, cited as current',
      'two jurisdictions mixed without a comparative framing that says so',
      'a doctrine described inconsistently with its own definition',
    ],
    requiresTheoreticalFramework: false,
    sensitiveNote: 'This is academic writing, not legal advice.',
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'SC',
      'HC',
      'AIR',
      'SCC',
      'IPC',
      'CrPC',
      'CPC',
      'BNS',
      'GDPR',
      'ICJ',
      'ECHR',
      'WTO',
      'UNCITRAL',
      'v',
      'vs',
    ],
  },
  {
    id: 'humanities_arts_v1',
    displayName: 'Humanities, Languages and Arts',
    departments: [
      'English',
      'Tamil',
      'Hindi',
      'History',
      'Philosophy',
      'Fine Arts',
      'Linguistics',
      'Performing Arts',
    ],
    defaultParadigms: ['textual', 'theoretical', 'qualitative'],
    entityTypes: [
      t(
        'PRIMARY_TEXT',
        'Primary text or work',
        'the text, artefact, performance or corpus studied, with author and edition',
      ),
      t('AUTHOR', 'Author or figure', 'the author, artist or historical figure'),
      t(
        'THEORY',
        'Theoretical lens',
        'the theory or critical approach applied, e.g. postcolonial theory, reader-response',
      ),
      t('PERIOD', 'Period', 'the historical period or era'),
      t('MOVEMENT', 'Movement or genre', 'a literary, artistic or intellectual movement or genre'),
      t(
        'ARCHIVE',
        'Archive or source collection',
        'an archive, manuscript collection or corpus consulted',
      ),
    ],
    defaultCitationStyle: 'mla',
    genericBackgroundCap: 0.25,
    minCitationsPerFactualParagraph: 1,
    recencyTarget: { years: 20, share: 0.25 },
    evidenceSources: ['the student’s library', 'Crossref', 'OpenAlex', 'archive catalogues'],
    specialChecks: ['D-HUM1'],
    terminology: [
      { preferred: 'postcolonial', avoid: ['post-colonial', 'post colonial'] },
      { preferred: 'close reading', avoid: ['close-reading'] },
    ],
    examinerFocus: [
      'a quotation from a primary text without edition and page, or longer than it needs to be',
      'a theoretical lens named but not defined, or applied inconsistently with its definition',
      'a period, context or movement stated without dates or evidence',
      'a secondary source’s reading presented as the primary text’s own words',
    ],
    requiresTheoreticalFramework: true,
    knownAbbreviations: [
      ...COMMON_KNOWN,
      'OED',
      'MLA',
      'BC',
      'CE',
      'ed',
      'eds',
      'trans',
      'vol',
      'ch',
    ],
  },
];

export const DEFAULT_DISCIPLINE_ID = 'engineering_core_v1';

export function disciplineProfile(id: string | null | undefined): DisciplineProfile {
  return (
    DISCIPLINE_PROFILES.find((profile) => profile.id === id) ??
    (DISCIPLINE_PROFILES.find(
      (profile) => profile.id === DEFAULT_DISCIPLINE_ID,
    ) as DisciplineProfile)
  );
}

/**
 * Suggests a discipline from the thesis's free-text field ("Mechanical Engineering",
 * "Commerce"). Word match against the departments and the display name; null when nothing
 * matches, so the screen asks rather than guesses.
 */
export function suggestDiscipline(field: string | null | undefined): DisciplineProfile | null {
  if (!field) return null;
  const words = field
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((word) => word.length > 1);
  if (words.length === 0) return null;
  let best: { profile: DisciplineProfile; score: number } | null = null;
  for (const profile of DISCIPLINE_PROFILES) {
    const haystack = [profile.displayName, ...profile.departments].join(' ').toLowerCase();
    const score = words.filter((word) => haystack.includes(word)).length;
    if (score > 0 && (!best || score > best.score)) best = { profile, score };
  }
  return best?.profile ?? null;
}
