export {
  type Block,
  blocksOf,
  CHAPTER_CHUNK_TOKENS,
  type ChapterChunkInput,
  type ChapterSentence,
  chunkChapter,
  sentencesOf,
} from './chapter-chunks.js';
export {
  batched,
  type Chunk,
  type ChunkInput,
  type ChunkOptions,
  chunkText,
  DEFAULT_OVERLAP_RATIO,
  DEFAULT_TARGET_TOKENS,
  isProseChunk,
  MIN_PROSE_WORDS,
  type PageSpan,
  type SectionSpan,
} from './chunker.js';
export {
  buildChapterMemory,
  type ContextChapter,
  type ContextClient,
  citedSourceCounts,
  docToText,
  pinsInScope,
  type RetrievalResult,
  type RetrievedPassage,
  retrievePassages,
} from './context.js';
export {
  type DocxComment,
  type DocxCommentImport,
  readDocxComments,
} from './extract/docx-comments.js';
export {
  type DocumentKind,
  detectGutter,
  detectSections,
  docxToHtml,
  type ExtractedDocument,
  type ExtractedPage,
  extractDocument,
  extractDocx,
  extractPdf,
  joinPages,
  looksLikeHeading,
  PAGE_BREAK,
  type PdfExtraction,
  pageText,
  pdfPageCount,
  type TextItem,
} from './extract/index.js';
export {
  DENSITY,
  densityFrom,
  type ThemeDensity,
  themeQuery,
  type YearCount,
} from './gap/density.js';
export {
  GAP_SIGNAL,
  type GapCandidate,
  type GapClass,
  type GapSignal,
  type GapTheme,
  gapSignals,
} from './gap/relevance.js';
export {
  type IndexingProvider,
  type IndexingStatus,
  type IndexName,
  type IndexVerdict,
  indexingOf,
  OpenAlexIndexing,
} from './indexing/provider.js';
export {
  type AlignmentLevel,
  type ImpactTier,
  JOURNAL_MATCH,
  type JournalCandidate,
  type JournalMatchProfile,
  type JournalScore,
  rankJournals,
  scopeAlignment,
  scoreJournal,
  tokensOf,
} from './journals/score.js';
export { OpenAlexSources, sourceShortId } from './journals/sources.js';
export {
  adviceFor,
  buildIndex,
  type ChunkForMatch,
  closeToPassages,
  contentWords,
  findParaphrases,
  longestCommonRun,
  PARAPHRASE,
  type ParaphraseMatch,
  type SentenceForMatch,
  SHINGLE,
  shingles,
  words,
} from './paraphrase.js';
export {
  type CandidateQuery,
  type ChapterChunkRow,
  type ChunkRow,
  EMBEDDING_DIMENSIONS,
  EmbeddingShapeError,
  findCandidates,
  findChapterNeighbours,
  type NeighbourChunk,
  type RawClient,
  replaceChapterChunks,
  replaceSourceChunks,
  shortReference,
  toVectorLiteral,
} from './pgvector.js';
export {
  buildQueryText,
  CANDIDATE_LIMIT,
  type Candidate,
  CITED_PENALTY,
  CREDIBILITY,
  credibility,
  FULL_TEXT_BOOST,
  isOffTopic,
  parsePassageId,
  passageId,
  type RankedCandidate,
  RELEVANCE_FLOOR,
  type RetrievalAction,
  rerank,
  SPREAD_FLOOR,
  SUB_THEME_BOOST,
  spreadCitations,
  stripUnknownCitations,
  TOP_K,
  topK,
} from './rank.js';
export {
  C4_RECALL_THRESHOLD,
  formatRecallReport,
  type IndexedChunk,
  locateQuote,
  normaliseForQuote,
  type QaQuestion,
  type QaSet,
  QUESTIONS_PER_PAPER,
  type QuestionOutcome,
  qaQuestionSchema,
  qaSetSchema,
  type RecallScore,
  readQaSet,
  scoreQuestion,
  scoreRecall,
} from './recall.js';
export {
  ARXIV,
  ArxivClient,
  type ArxivEntry,
  arxivSearchQuery,
  parseArxivFeed,
  workFromArxiv,
} from './scholarly/arxiv.js';
export { arxivAbsUrl, arxivDoi, arxivIdFromDoi, arxivIdFromUrl } from './scholarly/arxiv-id.js';
export {
  type BibEntry,
  type BibFormat,
  detectBibFormat,
  parseBibliography,
  parseBibtex,
  parseRis,
} from './scholarly/bibliography.js';
export { INDEX_BUDGET, type SearchFn, searchWithinBudget } from './scholarly/budget.js';
export {
  CORE_REQUESTS_PER_SECOND,
  CORE_SEARCH_LIMIT,
  CoreClient,
  type CoreFullText,
} from './scholarly/core.js';
export {
  cosine,
  DISCOVER,
  type DiscoveredWork,
  interleave,
  mergeWorks,
  normaliseDoi,
  normaliseTitle,
  OpenAlexDiscovery,
  openalexShortId,
  SemanticScholarClient,
  type WorkFilters,
} from './scholarly/discover.js';
export {
  EUROPE_PMC_REQUESTS_PER_SECOND,
  EuropePmcClient,
  type EuropePmcFullText,
  jatsToText,
} from './scholarly/europepmc.js';
export {
  FIRST_PAGE_CHARS,
  type FirstPage,
  joinBrokenWords,
  readFirstPage,
} from './scholarly/first-page.js';
export {
  FETCH_TIMEOUT_MS,
  type FullTextFailure,
  type FullTextFetchOptions,
  type FullTextResult,
  fetchOpenAccessPdf,
  MAX_PDF_BYTES,
  readableFullTextReason,
} from './scholarly/fulltext.js';
export {
  DEFAULT_ATTEMPTS,
  DEFAULT_REQUESTS_PER_SECOND,
  type FetchLike,
  RateLimiter,
  type ScholarlyClientOptions,
  ScholarlyError,
  ScholarlyHttp,
  type SharedGateOptions,
  type SlotStore,
  sharedGate,
} from './scholarly/http.js';
export {
  type BookRecord,
  detectPaperId,
  OpenLibraryClient,
  type PaperId,
  validIsbn,
} from './scholarly/ids.js';
export { keywordsOf, openAlexSearchText, topicSearchTerms } from './scholarly/keywords.js';
export { personName } from './scholarly/names.js';
export {
  type MatchedPassage,
  matchingPassage,
  PASSAGE,
  stemOf,
} from './scholarly/passage.js';
export {
  isNotASource,
  PUBMED,
  PubMedClient,
  type PubmedRecord,
  parsePubmedArticles,
  workFromPubmed,
} from './scholarly/pubmed.js';
export {
  CHAT_RESEARCH,
  type LibraryCoverage,
  libraryCoverage,
  planResearchQueries,
  type ResearchPlan,
  researchEmbedText,
} from './scholarly/research.js';
export {
  abstractFromInvertedIndex,
  CROSSREF_CANDIDATES,
  CrossrefClient,
  type CslAuthor,
  candidateScore,
  firstLine,
  type GapCheck,
  groundingLevelFor,
  journalCitednessOf,
  type OpenAccessLocation,
  OpenAlexClient,
  type OpenAlexSource,
  type OpenAlexWork,
  openAccessFromStatus,
  openAlexWorkMetrics,
  openalexSourceId,
  plainAbstract,
  RESOLUTION_THRESHOLD,
  type RelatedWork,
  type ResolvedSource,
  type Resolver,
  resolveByDoi,
  resolveReference,
  UNRESOLVED,
  UnpaywallClient,
  type WorkMetrics,
} from './scholarly/resolve.js';
export {
  type CslItem,
  cslToBibEntry,
  listZoteroCollections,
  nextLink,
  readZoteroItems,
  redactKey,
  ZOTERO_API,
  ZOTERO_IMPORT_CAP,
  ZOTERO_KEYS_URL,
  type ZoteroCollection,
  type ZoteroCredentials,
  ZoteroError,
  type ZoteroFailure,
  type ZoteroItems,
  type ZoteroOptions,
} from './scholarly/zotero.js';
export {
  type ActualExtraction,
  C3_THRESHOLDS,
  type ExpectedExtraction,
  type ExpectedReference,
  formatScoreTable,
  matchReferences,
  type PaperScore,
  REFERENCE_MATCH_THRESHOLD,
  scorePaper,
} from './scoring.js';
export {
  OVERLAP,
  type OverlapMatch,
  type OverlapReport,
  type OverlapSourceText,
  type OverlapVerdict,
  overlapReport,
  ShingleSimilarity,
  type SimilarityProvider,
} from './similarity/overlap.js';
export {
  approxTokens,
  CHARS_PER_TOKEN,
  jaccard,
  levenshtein,
  normalise,
  normaliseReference,
  referenceSimilarity,
  type Sentence,
  similarity,
  splitSentences,
  stripReferenceNumbering,
  tokenSet,
} from './text.js';
