export {
  batched,
  type Chunk,
  type ChunkInput,
  type ChunkOptions,
  chunkText,
  DEFAULT_OVERLAP_RATIO,
  DEFAULT_TARGET_TOKENS,
  type PageSpan,
  type SectionSpan,
} from './chunker.js';
export {
  buildQueryText,
  CANDIDATE_LIMIT,
  type Candidate,
  FULL_TEXT_BOOST,
  parsePassageId,
  passageId,
  type RankedCandidate,
  type RetrievalAction,
  rerank,
  SUB_THEME_BOOST,
  stripUnknownCitations,
  TOP_K,
  topK,
} from './rank.js';
export {
  DEFAULT_ATTEMPTS,
  DEFAULT_REQUESTS_PER_SECOND,
  type FetchLike,
  RateLimiter,
  type ScholarlyClientOptions,
  ScholarlyError,
  ScholarlyHttp,
} from './scholarly/http.js';
export {
  CROSSREF_CANDIDATES,
  CrossrefClient,
  type CslAuthor,
  candidateScore,
  groundingLevelFor,
  type OpenAccessLocation,
  OpenAlexClient,
  RESOLUTION_THRESHOLD,
  type ResolvedSource,
  type Resolver,
  resolveReference,
  UNRESOLVED,
  UnpaywallClient,
} from './scholarly/resolve.js';
export {
  type ActualExtraction,
  C3_THRESHOLDS,
  type ExpectedExtraction,
  type ExpectedReference,
  formatScoreTable,
  matchReferences,
  type PaperScore,
  REFERENCE_MATCH_THRESHOLD,
  scorePaper,
} from './scoring.js';
export {
  approxTokens,
  CHARS_PER_TOKEN,
  jaccard,
  levenshtein,
  normalise,
  normaliseReference,
  referenceSimilarity,
  type Sentence,
  similarity,
  splitSentences,
  stripReferenceNumbering,
  tokenSet,
} from './text.js';
