-- Thesis Copilot initial migration.
--
-- Extensions, the UUID v7 generator and the HNSW vector indexes are hand-written per PRD §8
-- ("Hand-written migration additions"). Everything below the extension block is generated by
-- `prisma migrate diff` from schema.prisma.

-- ---------------------------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS vector;

-- `gen_random_bytes`, used by uuid_generate_v7() below, comes from pgcrypto.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- PRD §8 offers `CREATE EXTENSION pg_uuidv7` "or implement uuid_generate_v7() as a SQL function".
-- Checked before choosing (PRD §0.3 rule 1): the pgvector/pgvector:pg16 image ships `vector` but
-- NOT `pg_uuidv7`, so the function is implemented here in plain SQL.
--
--   $ docker run --rm pgvector/pgvector:pg16 \
--       sh -c 'ls /usr/share/postgresql/16/extension/ | grep -iE "uuidv7|^vector"'
--   vector--*.sql ... vector.control          # no pg_uuidv7
--
-- Layout per RFC 9562 §5.7:
--   bits 0-47   unix timestamp in milliseconds, big-endian
--   bits 48-51  version (0111 = 7)
--   bits 52-63  random
--   bits 64-65  variant (10)
--   bits 66-127 random
-- The result is time-ordered, which is why PRD §0.2 chose v7: index locality on insert.

CREATE OR REPLACE FUNCTION uuid_generate_v7()
RETURNS uuid
AS $$
DECLARE
  unix_ts_ms bytea;
  uuid_bytes bytea;
BEGIN
  unix_ts_ms := substring(int8send((extract(epoch FROM clock_timestamp()) * 1000)::bigint) FROM 3);

  -- 10 random bytes fill everything after the 48-bit timestamp.
  uuid_bytes := unix_ts_ms || gen_random_bytes(10);

  -- Byte 6: high nibble = version 7, low nibble stays random.  (b & 0x0F) | 0x70
  uuid_bytes := set_byte(uuid_bytes, 6, (get_byte(uuid_bytes, 6) & 15) | 112);

  -- Byte 8: top two bits = variant 0b10, low six stay random.    (b & 0x3F) | 0x80
  uuid_bytes := set_byte(uuid_bytes, 8, (get_byte(uuid_bytes, 8) & 63) | 128);

  RETURN encode(uuid_bytes, 'hex')::uuid;
END
$$
LANGUAGE plpgsql
VOLATILE;

COMMENT ON FUNCTION uuid_generate_v7() IS
  'RFC 9562 UUID v7 (time-ordered). Default for every primary key — PRD §0.2.';

-- ---------------------------------------------------------------------------------------------
-- Tables, enums, indexes and foreign keys
-- Generated by: prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
-- ---------------------------------------------------------------------------------------------

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "vector";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('STUDENT', 'GUIDE', 'INSTITUTION_ADMIN', 'SUPERADMIN');

-- CreateEnum
CREATE TYPE "Plan" AS ENUM ('FREE_TRIAL', 'STUDENT_MONTHLY', 'STUDENT_ANNUAL', 'INSTITUTION_SEAT');

-- CreateEnum
CREATE TYPE "EntryPath" AS ENUM ('A_TOPIC', 'B_PAPER');

-- CreateEnum
CREATE TYPE "Template" AS ENUM ('STEM_EMPIRICAL', 'QUALITATIVE', 'COMPILATION');

-- CreateEnum
CREATE TYPE "SourceStatus" AS ENUM ('PENDING', 'RESOLVED', 'UNRESOLVED', 'FAILED');

-- CreateEnum
CREATE TYPE "GroundingLevel" AS ENUM ('NONE', 'ABSTRACT', 'FULL_TEXT');

-- CreateEnum
CREATE TYPE "Provenance" AS ENUM ('HUMAN', 'ASSIST', 'DRAFT', 'COMMAND', 'HUMAN_EDITED');

-- CreateEnum
CREATE TYPE "AiAction" AS ENUM ('ASSIST', 'DRAFT', 'CITE', 'CHAT', 'COMMAND', 'EXTRACT', 'OUTLINE', 'STYLE_PROFILE', 'SEARCH_QUERIES', 'COHERENCE', 'CLASSIFY_COMMENT', 'SCOPED_REVISION', 'PARSE_CITATION', 'EMBED');

-- CreateEnum
CREATE TYPE "FlagType" AS ENUM ('TERM_DRIFT', 'CLAIM_CONTRADICTION', 'UNSUPPORTED_CLAIM', 'CITATION_INTEGRITY', 'OUTLINE_DRIFT');

-- CreateEnum
CREATE TYPE "Severity" AS ENUM ('INFO', 'WARN', 'ERROR');

-- CreateEnum
CREATE TYPE "CommentClass" AS ENUM ('SUBSTANTIVE', 'CLARIFICATION', 'MECHANICAL');

-- CreateEnum
CREATE TYPE "CommentStatus" AS ENUM ('OPEN', 'ACCEPTED', 'EDITED', 'REJECTED');

-- CreateTable
CREATE TABLE "User" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "email" TEXT NOT NULL,
    "name" TEXT,
    "role" "Role" NOT NULL DEFAULT 'STUDENT',
    "plan" "Plan" NOT NULL DEFAULT 'FREE_TRIAL',
    "institutionId" UUID,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Institution" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "name" TEXT NOT NULL,
    "seats" INTEGER NOT NULL DEFAULT 0,
    "templateId" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Institution_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Document" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "ownerId" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "entryPath" "EntryPath" NOT NULL,
    "template" "Template",
    "field" TEXT,
    "language" TEXT NOT NULL DEFAULT 'en',
    "citationStyle" TEXT NOT NULL DEFAULT 'apa',
    "institutionTemplateId" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DocumentMemory" (
    "documentId" UUID NOT NULL,
    "scope" JSONB NOT NULL,
    "outline" JSONB NOT NULL,
    "glossary" JSONB NOT NULL,
    "styleProfile" JSONB,
    "gapMap" JSONB,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DocumentMemory_pkey" PRIMARY KEY ("documentId")
);

-- CreateTable
CREATE TABLE "SeedPaper" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "documentId" UUID NOT NULL,
    "fileKey" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "extraction" JSONB,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SeedPaper_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Chapter" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "documentId" UUID NOT NULL,
    "outlineNodeId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "content" JSONB NOT NULL,
    "wordCount" INTEGER NOT NULL DEFAULT 0,
    "scopeNote" TEXT,
    "lastCheckedAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Chapter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChapterSourcePin" (
    "chapterId" UUID NOT NULL,
    "sourceId" UUID NOT NULL,

    CONSTRAINT "ChapterSourcePin_pkey" PRIMARY KEY ("chapterId","sourceId")
);

-- CreateTable
CREATE TABLE "Source" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "documentId" UUID NOT NULL,
    "status" "SourceStatus" NOT NULL DEFAULT 'PENDING',
    "rawReference" TEXT,
    "doi" TEXT,
    "openalexId" TEXT,
    "title" TEXT,
    "authors" JSONB,
    "year" INTEGER,
    "venue" TEXT,
    "type" TEXT,
    "cslJson" JSONB,
    "oaStatus" TEXT,
    "fileKey" TEXT,
    "groundingLevel" "GroundingLevel" NOT NULL DEFAULT 'NONE',
    "subTheme" TEXT,
    "citationCount" INTEGER,
    "isPreprint" BOOLEAN NOT NULL DEFAULT false,
    "isRetracted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Source_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SourceChunk" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "sourceId" UUID NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "page" INTEGER,
    "charStart" INTEGER,
    "charEnd" INTEGER,
    "section" TEXT,
    "text" TEXT NOT NULL,
    "tokenCount" INTEGER NOT NULL,
    "embedding" vector(1024),

    CONSTRAINT "SourceChunk_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChapterChunk" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "chapterId" UUID NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "from" INTEGER NOT NULL,
    "to" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "embedding" vector(1024),

    CONSTRAINT "ChapterChunk_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Citation" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "chapterId" UUID NOT NULL,
    "sourceId" UUID NOT NULL,
    "chunkId" UUID,
    "nodeKey" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'parenthetical',
    "locator" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Citation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SearchCandidate" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "runId" UUID NOT NULL,
    "documentId" UUID NOT NULL,
    "openalexId" TEXT,
    "doi" TEXT,
    "title" TEXT NOT NULL,
    "abstract" TEXT,
    "year" INTEGER,
    "venue" TEXT,
    "citationCount" INTEGER,
    "isPreprint" BOOLEAN NOT NULL DEFAULT false,
    "oaStatus" TEXT,
    "theme" TEXT,
    "score" DOUBLE PRECISION,
    "selected" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SearchCandidate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DocumentVersion" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "documentId" UUID NOT NULL,
    "chapterId" UUID,
    "snapshotKey" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DocumentVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SuggestionEvent" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "userId" UUID NOT NULL,
    "documentId" UUID NOT NULL,
    "chapterId" UUID,
    "action" "AiAction" NOT NULL,
    "shownChars" INTEGER NOT NULL,
    "keptChars" INTEGER NOT NULL DEFAULT 0,
    "outcome" TEXT NOT NULL,
    "latencyMs" INTEGER NOT NULL,
    "ttfbMs" INTEGER,
    "guided" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SuggestionEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AiCallLog" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "userId" UUID NOT NULL,
    "documentId" UUID,
    "action" "AiAction" NOT NULL,
    "model" TEXT NOT NULL,
    "inputTokens" INTEGER NOT NULL,
    "cachedInputTokens" INTEGER NOT NULL DEFAULT 0,
    "cacheWriteTokens" INTEGER NOT NULL DEFAULT 0,
    "outputTokens" INTEGER NOT NULL,
    "costMicroInr" BIGINT NOT NULL,
    "latencyMs" INTEGER NOT NULL,
    "ok" BOOLEAN NOT NULL DEFAULT true,
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AiCallLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UsageLedger" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "userId" UUID NOT NULL,
    "period" TEXT NOT NULL,
    "action" "AiAction" NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "UsageLedger_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subscription" (
    "userId" UUID NOT NULL,
    "provider" TEXT NOT NULL DEFAULT 'razorpay',
    "providerSubId" TEXT,
    "plan" "Plan" NOT NULL,
    "status" TEXT NOT NULL,
    "currentPeriodEnd" TIMESTAMP(3) NOT NULL,
    "cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT false,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Subscription_pkey" PRIMARY KEY ("userId")
);

-- CreateTable
CREATE TABLE "GuideShare" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "documentId" UUID NOT NULL,
    "guideEmail" TEXT NOT NULL,
    "guideUserId" UUID,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GuideShare_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Comment" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "documentId" UUID NOT NULL,
    "chapterId" UUID,
    "authorEmail" TEXT NOT NULL,
    "anchorKey" TEXT,
    "quotedText" TEXT,
    "body" TEXT NOT NULL,
    "class" "CommentClass",
    "status" "CommentStatus" NOT NULL DEFAULT 'OPEN',
    "suggestedRevision" TEXT,
    "resolutionNote" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Comment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CoherenceFlag" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "documentId" UUID NOT NULL,
    "chapterId" UUID NOT NULL,
    "from" INTEGER NOT NULL,
    "to" INTEGER NOT NULL,
    "type" "FlagType" NOT NULL,
    "severity" "Severity" NOT NULL,
    "description" TEXT NOT NULL,
    "suggestion" TEXT,
    "relatedChapterId" UUID,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "runId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CoherenceFlag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InstitutionTemplate" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "name" TEXT NOT NULL,
    "spec" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "InstitutionTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FeatureFlag" (
    "key" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "rules" JSONB,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FeatureFlag_pkey" PRIMARY KEY ("key")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "Document_ownerId_idx" ON "Document"("ownerId");

-- CreateIndex
CREATE INDEX "Chapter_documentId_order_idx" ON "Chapter"("documentId", "order");

-- CreateIndex
CREATE UNIQUE INDEX "Chapter_documentId_outlineNodeId_key" ON "Chapter"("documentId", "outlineNodeId");

-- CreateIndex
CREATE INDEX "Source_documentId_idx" ON "Source"("documentId");

-- CreateIndex
CREATE INDEX "Source_doi_idx" ON "Source"("doi");

-- CreateIndex
CREATE INDEX "SourceChunk_sourceId_ordinal_idx" ON "SourceChunk"("sourceId", "ordinal");

-- CreateIndex
CREATE INDEX "ChapterChunk_chapterId_ordinal_idx" ON "ChapterChunk"("chapterId", "ordinal");

-- CreateIndex
CREATE UNIQUE INDEX "Citation_chapterId_nodeKey_key" ON "Citation"("chapterId", "nodeKey");

-- CreateIndex
CREATE INDEX "SearchCandidate_documentId_runId_idx" ON "SearchCandidate"("documentId", "runId");

-- CreateIndex
CREATE INDEX "DocumentVersion_documentId_createdAt_idx" ON "DocumentVersion"("documentId", "createdAt");

-- CreateIndex
CREATE INDEX "SuggestionEvent_userId_createdAt_idx" ON "SuggestionEvent"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "SuggestionEvent_documentId_createdAt_idx" ON "SuggestionEvent"("documentId", "createdAt");

-- CreateIndex
CREATE INDEX "AiCallLog_userId_createdAt_idx" ON "AiCallLog"("userId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "UsageLedger_userId_period_action_key" ON "UsageLedger"("userId", "period", "action");

-- CreateIndex
CREATE UNIQUE INDEX "GuideShare_token_key" ON "GuideShare"("token");

-- CreateIndex
CREATE INDEX "Comment_documentId_status_idx" ON "Comment"("documentId", "status");

-- CreateIndex
CREATE INDEX "CoherenceFlag_documentId_status_idx" ON "CoherenceFlag"("documentId", "status");

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "Institution"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Document" ADD CONSTRAINT "Document_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DocumentMemory" ADD CONSTRAINT "DocumentMemory_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SeedPaper" ADD CONSTRAINT "SeedPaper_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Chapter" ADD CONSTRAINT "Chapter_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChapterSourcePin" ADD CONSTRAINT "ChapterSourcePin_chapterId_fkey" FOREIGN KEY ("chapterId") REFERENCES "Chapter"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChapterSourcePin" ADD CONSTRAINT "ChapterSourcePin_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "Source"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Source" ADD CONSTRAINT "Source_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SourceChunk" ADD CONSTRAINT "SourceChunk_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "Source"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChapterChunk" ADD CONSTRAINT "ChapterChunk_chapterId_fkey" FOREIGN KEY ("chapterId") REFERENCES "Chapter"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Citation" ADD CONSTRAINT "Citation_chapterId_fkey" FOREIGN KEY ("chapterId") REFERENCES "Chapter"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Citation" ADD CONSTRAINT "Citation_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "Source"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DocumentVersion" ADD CONSTRAINT "DocumentVersion_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AiCallLog" ADD CONSTRAINT "AiCallLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UsageLedger" ADD CONSTRAINT "UsageLedger_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GuideShare" ADD CONSTRAINT "GuideShare_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GuideShare" ADD CONSTRAINT "GuideShare_guideUserId_fkey" FOREIGN KEY ("guideUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CoherenceFlag" ADD CONSTRAINT "CoherenceFlag_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------------------------
-- Vector indexes (PRD §8, "Hand-written migration additions")
--
-- HNSW with cosine distance. Prisma cannot express these, so they live here.
-- ---------------------------------------------------------------------------------------------

CREATE INDEX source_chunk_embedding_hnsw
  ON "SourceChunk" USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE INDEX chapter_chunk_embedding_hnsw
  ON "ChapterChunk" USING hnsw (embedding vector_cosine_ops);
