export {
  type AnchorMatch,
  type AnchorSentence,
  findAnchor,
  normalise,
  similarity,
} from './builder/anchor.js';
export {
  ASSIST,
  type AssistBuildInput,
  assistCachedBlock,
  assistUserMessage,
  buildAssistRequest,
  type PromptPassage,
} from './builder/assist.js';
export {
  activeFilters,
  buildChatRequest,
  CHAT,
  type ChatBuildInput,
  type ChatFilters,
  type ChatOutcome,
  type ChatPostProcess,
  type ChatTurn,
  chatUserMessage,
  FILTERED_OUT_REPLY,
  mockChatFor,
  NAMED_EMPTY_REPLY,
  NOT_ENOUGH_PREFIX,
  OFF_TOPIC_REPLY,
  postProcessChat,
  WRITING_REDIRECT_PREFIX,
} from './builder/chat.js';
export {
  buildCiteRequest,
  CITE,
  type CiteBuildInput,
  type CiteCandidate,
  type CiteResult,
  type ClaimReason,
  type ClaimVerdict,
  citeCandidateSchema,
  citeResultSchema,
  citeUserMessage,
  detectClaim,
  endsSentence,
  lastCompleteSentence,
  mockCiteResponse,
  usableCandidates,
} from './builder/cite.js';
export {
  buildCiteParseRequest,
  CITE_PARSE,
  type CiteParseInput,
  CSL_TYPES,
  doiIn,
  mockCiteParseResponse,
  type ParsedCitation,
  parsedCitationSchema,
  referenceLinesIn,
} from './builder/cite-parse.js';
export {
  buildCiteRoleRequest,
  CITATION_ROLES,
  CITE_ROLE,
  type CitationRole,
  type CiteRoleInput,
  type CiteRolePostProcess,
  citeRoleCachedBlock,
  citeRoleUserMessage,
  mockCiteRoleResponse,
  postProcessCiteRole,
} from './builder/cite-role.js';
export {
  buildChapterSummaryRequest,
  buildClaimsRequest,
  buildContradictionRequest,
  buildOutlineDriftRequest,
  buildSupportRequest,
  buildTermDriftRequest,
  buildUnsupportedRequest,
  type ClaimsResult,
  type ClaimWithPassages,
  COHERENCE,
  type ContradictionResult,
  claimsSchema,
  contradictionSchema,
  flagFingerprint,
  mightNeedSupport,
  mockCoherenceResponse,
  type OutlineDriftResult,
  outlineDriftSchema,
  SUPPORT_VERDICTS,
  type SupportItem,
  type SupportResult,
  type SupportVerdict,
  supportSchema,
  type TermDriftResult,
  type TermSentence,
  termDriftSchema,
  termDriftUserMessage,
  type UnsupportedResult,
  unsupportedSchema,
  verbatimQuote,
} from './builder/coherence.js';
export {
  buildCommandRequest,
  COMMAND,
  COMMAND_LABELS,
  COMMANDS,
  type CommandBuildInput,
  type CommandName,
  type CommandPostProcess,
  commandResultSchema,
  commandUserMessage,
  type DiffOp,
  diffWords,
  mockCommandFor,
  mockCommandResponse,
  postProcessCommand,
} from './builder/command.js';
export {
  buildClassifyRequest,
  buildReviseRequest,
  type ClassifyResult,
  COMMENT,
  COMMENT_CLASSES,
  type CommentClass,
  classifySchema,
  mockClassifyResponse,
  mockRevisionFor,
  NEEDS_INPUT_RE,
  postProcessRevision,
  type ReviseInput,
  type RevisionPostProcess,
  reviseUserMessage,
} from './builder/comment.js';
export {
  buildDraftRequest,
  canDraft,
  countDraftWords,
  DRAFT,
  type DraftBuildInput,
  type DraftPostProcess,
  type DraftResult,
  type DraftSection,
  draftResultSchema,
  draftToProseMirror,
  draftUserMessage,
  filterDraftParagraphs,
  mockDraftFor,
  NEEDS_SOURCE_RE,
  NO_SOURCES_MESSAGE,
  postProcessDraft,
} from './builder/draft.js';
export {
  buildMemoryBlock,
  type GlossaryEntry,
  MEMORY_BUDGET_TOKENS,
  type MemoryBlock,
  type MemoryInput,
  type MemoryScope,
  type MemoryTrim,
  renderOutline,
  type StyleProfile,
} from './builder/memory.js';
export {
  buildOutlineRequest,
  enforceTemplateShape,
  type GapMapTheme,
  mockOutlineResponse,
  normaliseOutline,
  OUTLINE,
  type OutlineBuildInput,
  outlineRequestSchema,
  outlineResultSchema,
  outlineUserMessage,
  readOutlineResult,
  roleForChapter,
} from './builder/outline.js';
export {
  CITE_RE,
  cutAfterSecondSentence,
  type PostProcessInput,
  type PostProcessResult,
  postProcessAssist,
  removeLeadingOverlap,
  stripUnknownCitations,
} from './builder/postprocess.js';
export {
  buildProofreadRequest,
  type Correction,
  changedWords,
  correctionSize,
  kindOf,
  mockProofreadResponse,
  narrowCorrection,
  PROOFREAD,
  PROOFREAD_KINDS,
  PROOFREAD_TOKENS_PER_WORD,
  type ProofreadKind,
  type ProofreadResult,
  type ProofreadSentence,
  postProcessProofread,
  proofreadSchema,
  splitCorrection,
} from './builder/proofread.js';
export {
  buildProposalRequest,
  clarifiedTopic,
  type GapCheckInput,
  type GapCheckWork,
  MOCK_KEEP_ASKING,
  mayAskAnotherQuestion,
  mockProposalFor,
  PROPOSAL,
  type ProposalBuildInput,
  type ProposalReply,
  type ProposalSkeleton,
  type ProposalTurn,
  parseProposalReply,
  questionsAsked,
  renderGapCheck,
  SKELETON_INSTRUCTION,
  skeletonSchema,
} from './builder/proposal.js';
export {
  filterSentences,
  isRoadmap,
  isUncitedAttribution,
  nearDuplicate,
  opensWithConnective,
  type QualityDrops,
  splitSentences,
} from './builder/quality.js';
export {
  buildQueriesRequest,
  cleanQueries,
  mockQueriesResponse,
  QUERIES,
  QUERY_ANGLES,
  type QueriesInput,
  type QueriesResult,
  queriesSchema,
  queriesUserMessage,
  renderScope,
  type ScopeForQueries,
} from './builder/queries.js';
export {
  buildSectionScopeRequest,
  mockSectionScopeResponse,
  SECTION_SCOPE,
  type SectionScopeInput,
  type SectionScopeResult,
  sectionScopeSchema,
  sectionScopeUserMessage,
} from './builder/section-scope.js';
export {
  buildStyleRequest,
  humanText,
  mockStyleResponse,
  STYLE,
  type StyleBuildInput,
  type StyleProfileResult,
  styleProfileSchema,
  trimSample,
} from './builder/style.js';
export {
  buildThemesRequest,
  type GapTheme,
  mockThemesResponse,
  normaliseThemes,
  THEMES,
  type ThemeCandidate,
  type ThemesInput,
  type ThemesResult,
  themesSchema,
  themesUserMessage,
} from './builder/themes.js';
export { approxTokens, CHARS_PER_TOKEN, headByTokens, tailByTokens } from './builder/tokens.js';
export {
  buildVivaFeedbackRequest,
  buildVivaQuestionsRequest,
  mockVivaFeedbackResponse,
  mockVivaQuestionsResponse,
  postProcessVivaFeedback,
  postProcessVivaQuestions,
  VIVA,
  VIVA_KINDS,
  VIVA_VERDICTS,
  type VivaFeedback,
  type VivaFeedbackResult,
  type VivaKind,
  type VivaPassage,
  type VivaQuestionDraft,
  type VivaQuestionsResult,
  type VivaVerdict,
  vivaFeedbackSchema,
  vivaQuestionsSchema,
} from './builder/viva.js';
export {
  buildCrossPaperRequest,
  type CrossPaperInput,
  type CrossPaperResult,
  crossPaperSchema,
  crossPaperUserMessage,
  type GlossaryValue,
  mergeTerminology,
  mockCrossPaperResponse,
  XPAPER,
} from './builder/xpaper.js';
export {
  buildExtractionRequest,
  buildExtractionUserMessage,
  DEFAULT_MAX_PART_CHARS,
  ExtractionFailed,
  type ExtractionPart,
  extractPaper,
  findReferenceSection,
  MAX_PARTS,
  mergeExtractions,
  splitForExtraction,
} from './extraction.js';
export { createProviders, type Providers } from './factory.js';
export {
  countSentences,
  formatGoldenReport,
  type GoldenFailure,
  type GoldenOutcome,
  type GoldenPassage,
  type GoldenScenario,
  goldenScenarioSchema,
  goldenSetSchema,
  judge,
} from './golden.js';
export {
  deriveExtraction,
  mockExtractionResponse,
  paperTextFromMessage,
} from './mock-extraction.js';
export {
  extractFencedBlocks,
  type LoadedPrompt,
  listPromptFiles,
  loadAllPrompts,
  loadPrompt,
  PROMPT_NAMES,
  PROMPTS_DIR,
  type PromptName,
} from './prompts.js';
export {
  AnthropicLlmProvider,
  type AnthropicProviderOptions,
  toTokenUsage,
  VoyageEmbeddingProvider,
} from './providers/anthropic.js';
export {
  type MockEmbeddingOptions,
  MockEmbeddingProvider,
  MockLlmProvider,
  type MockProviderOptions,
  type MockResponse,
} from './providers/mock.js';
export {
  providerForModel,
  TieredLlmProvider,
  type Vendor,
} from './providers/routing.js';
export { renderTemplate, type TemplateData } from './template.js';
export {
  type AiAction,
  type EmbeddingProvider,
  type LlmChunk,
  type LlmProvider,
  LlmProviderError,
  type LlmRequest,
  type LlmResult,
  LlmValidationError,
  type Message,
  type Tier,
  type TokenUsage,
} from './types.js';
