export * from './chapter-build.js';
export {
  CHART_LIMITS,
  CHART_TYPES,
  type ChartSpec,
  type ChartType,
  chartSpecSchema,
} from './chart.js';
export {
  formatRef,
  kindOfNode,
  type NumberedTarget,
  numberingMap,
  numberTargets,
  type RefKind,
  refIdOf,
} from './cross-ref.js';
export {
  DIAGRAM_DIRECTIONS,
  DIAGRAM_LIMITS,
  type DiagramEdge,
  type DiagramNode,
  type DiagramSpec,
  diagramSpecSchema,
  type ParsedDiagram,
  parseDiagram,
} from './diagram.js';
export { CITATION_MODES, type CitationMode, citationModeSchema } from './export-options.js';
export {
  emptyExtraction,
  type Finding,
  findingSchema,
  type GapAnalysis,
  type GapItem,
  type PaperExtraction,
  type PaperReference,
  type PaperSection,
  paperExtractionSchema,
  paperSectionSchema,
  referenceSchema,
  type Terminology,
  THESIS_REFERENCE_RANGE,
  terminologySchema,
} from './extraction.js';
export { analyseGap, draftScopeFrom, type ProposalScope } from './gap.js';
export {
  type CoherenceRunJob,
  type DraftSectionJob,
  type ExtractPaperJob,
  type FindSourcesJob,
  type GenerateOutlineJob,
  type IndexSourceJob,
  JOB_RETRY,
  type JobPayloads,
  jobId,
  jobKeyDigest,
  QUEUE_NAMES,
  type QueueName,
  type ResolveReferenceJob,
  SEED_PAPER_STATUSES,
  type SearchLiteratureJob,
  type SeedPaperStatus,
} from './jobs.js';
export * from './lifecycle.js';
export {
  DEFAULT_CHAPTER_TITLE,
  findOutlineNode,
  firstChapterOutline,
  type OutlineNode,
  outlineNodeId,
  outlineNodeSchema,
  outlineSchema,
  readOutline,
  scopeWithSection,
  sectionUnderHeading,
  walkOutline,
} from './outline.js';
export {
  bibliographySchema,
  captionSchema,
  FIELD_LABELS,
  FRONT_MATTER_IDS,
  type FrontMatterId,
  type FrontMatterSection,
  fieldLabel,
  fontSchema,
  frontMatterSectionSchema,
  headingsSchema,
  marginsSchema,
  numberingSchema,
  PAGE_SIZES,
  pageSchema,
  readTemplateSpec,
  readThesisDetails,
  type TemplateSpec,
  type ThesisDetails,
  templateSpecSchema,
  thesisDetailsSchema,
} from './template.js';
