export * from './chapter-build.js';
export {
  CHART_LIMITS,
  CHART_TYPES,
  type ChartSpec,
  type ChartType,
  chartSpecSchema,
} from './chart.js';
export { COLLECTION_NAME_MAX } from './collections.js';
export {
  formatRef,
  kindOfNode,
  type NumberedTarget,
  numberingMap,
  numberTargets,
  type RefKind,
  refIdOf,
} from './cross-ref.js';
export {
  DIAGRAM_DIRECTIONS,
  DIAGRAM_LIMITS,
  type DiagramEdge,
  type DiagramNode,
  type DiagramSpec,
  diagramSpecSchema,
  type ParsedDiagram,
  parseDiagram,
} from './diagram.js';
export {
  applyLayout,
  type ExportLayout,
  exportLayoutSchema,
  LAYOUT_FONTS,
  LAYOUT_MARGINS,
  LAYOUT_PRESETS,
  LAYOUT_SIZES,
  LAYOUT_SPACINGS,
  type LayoutMargins,
  type LayoutPreset,
  MARGIN_MM,
  type ResolvedLayout,
  resolveLayout,
} from './export-layout.js';
export { CITATION_MODES, type CitationMode, citationModeSchema } from './export-options.js';
export {
  emptyExtraction,
  type Finding,
  findingSchema,
  type GapAnalysis,
  type GapItem,
  type PaperExtraction,
  type PaperReference,
  type PaperSection,
  paperExtractionSchema,
  paperSectionSchema,
  referenceSchema,
  type Terminology,
  THESIS_REFERENCE_RANGE,
  terminologySchema,
} from './extraction.js';
export {
  FONT_STYLE_DOCX,
  FONT_STYLES,
  type FontStyle,
  isFontStyle,
  readFontStyle,
} from './font-style.js';
export { analyseGap, draftScopeFrom, type ProposalScope } from './gap.js';
export {
  type CoherenceRunJob,
  type DraftSectionJob,
  type ExaminerQuestion,
  type ExaminerReviewJob,
  type ExaminerReviewRecord,
  type ExaminerStrength,
  type ExtractPaperJob,
  type FindSourcesJob,
  type GenerateOutlineJob,
  type IndexSourceJob,
  indexJobId,
  JOB_RETRY,
  JOB_WATCH,
  type JobPayloads,
  jobId,
  jobKeyDigest,
  jobWatchKey,
  QUEUE_NAMES,
  type QueueName,
  type ResolveReferenceJob,
  SEED_PAPER_STATUSES,
  type SearchLiteratureJob,
  type SeedPaperStatus,
} from './jobs.js';
export * from './lifecycle.js';
export {
  DEFAULT_CHAPTER_TITLE,
  findOutlineNode,
  firstChapterOutline,
  headingKey,
  isGenericSectionTitle,
  type OutlineNode,
  outlineNodeId,
  outlineNodeSchema,
  outlineSchema,
  readOutline,
  scopeWithSection,
  sectionUnderHeading,
  walkOutline,
} from './outline.js';
export {
  READER_CONTEXT_CHARS,
  READER_HIGHLIGHT_QUOTE_MAX,
  READER_HIGHLIGHTS_PER_SOURCE_MAX,
  READER_NOTE_MAX,
  type ReaderHighlight,
  type ReaderHighlightColour,
  type ReaderHighlightCreate,
  type ReaderHighlightUpdate,
  readerHighlightColour,
  readerHighlightCreate,
  readerHighlightUpdate,
} from './reader-highlights.js';
export {
  applySetupUpdate,
  isUntouchedNewThesis,
  namesATopic,
  newSetupCard,
  readSetupCard,
  SETUP_STEPS,
  type SetupCard,
  type SetupStep,
  type SetupUpdate,
  setupCardSchema,
  setupStepNumber,
  setupUpdateSchema,
  UNTITLED_THESIS,
  UNTOUCHED_HIDE_MS,
} from './setup-card.js';
export {
  DEFAULT_SOURCE_PREFS,
  INDEX_LIST_LABELS,
  INDEX_LISTS,
  type IndexList,
  listedInFilter,
  meetsSourcePrefs,
  OPENALEX_LISTED_IN,
  readSourcePrefs,
  type SourcePrefs,
  sourcePrefsSchema,
} from './source-prefs.js';
export {
  bibliographySchema,
  captionSchema,
  FIELD_LABELS,
  FRONT_MATTER_IDS,
  type FrontMatterId,
  type FrontMatterSection,
  fieldLabel,
  fontSchema,
  frontMatterSectionSchema,
  headingsSchema,
  marginsSchema,
  numberingSchema,
  PAGE_SIZES,
  pageSchema,
  readTemplateSpec,
  readThesisDetails,
  type TemplateSpec,
  type ThesisDetails,
  templateSpecSchema,
  thesisDetailsSchema,
} from './template.js';
export {
  colorsOf,
  HIGHLIGHT_COLORS,
  HIGHLIGHT_PRINT,
  type HighlightColor,
  isHighlightColor,
  isTextColor,
  TEXT_COLOR_PRINT,
  TEXT_COLORS,
  type TextColor,
} from './text-colors.js';
