/**
 * Better Auth configuration — PRD §7.2 (Better Auth, email OTP + Google, session cookies, role
 * claims) and §12.1 (Secure, HttpOnly, SameSite=Lax cookies).
 *
 * Google is configured only when both credentials are present. PHASES PHASE-0 allows Google to be
 * stubbed until keys exist; email OTP alone is enough to sign in, so a missing Google key disables
 * that button rather than blocking boot.
 */

import type { Env } from '@tc/config';
import type { PrismaClient } from '@tc/db';
import { betterAuth } from 'better-auth';
import { prismaAdapter } from 'better-auth/adapters/prisma';
import { emailOTP } from 'better-auth/plugins';
import { ConsoleMailer, type Mail, type Mailer } from '../../common/mailer.js';
import { claimInstitutionInvite } from '../institution/claim-invite.js';
import { rememberDevOtp } from './dev-otp.js';

export type SendOtp = (input: { email: string; otp: string; type: string }) => Promise<void>;

/**
 * In development the one-time code is printed to the console instead of emailed, so the app runs
 * without a mail provider. `packages/config` requires a real transport in production.
 */
const consoleOtp: SendOtp = async ({ email, otp, type }) => {
  console.log(`[auth] one-time code for ${email} (${type}): ${otp}`);
  if (process.env.NODE_ENV !== 'production') rememberDevOtp(email, otp);
};

/** Ten minutes, matching `expiresIn` on the plugin below. */
export const OTP_MINUTES = 10;

/** The one-time-code email. Plain text: the code is the whole message, and nothing should distract from it. */
export function otpMail(input: { email: string; otp: string; type: string }): Mail {
  const purpose = input.type === 'sign-in' ? 'sign in to' : 'confirm your email address for';
  return {
    to: [input.email],
    subject: `${input.otp} is your Thesis Copilot code`,
    text:
      `Use this code to ${purpose} Thesis Copilot:

    ${input.otp}

` +
      `It expires in ${OTP_MINUTES} minutes. If you did not ask for it, ignore this email — ` +
      'nobody can use the code without access to this inbox.',
  };
}

/**
 * How the code reaches the student: by email through the configured mailer, or — when the mailer
 * is the console one, i.e. no transport is configured — printed to the API console as before.
 * Outside production the dev OTP sink is fed either way, so the E2E can still sign in when a real
 * transport is set locally.
 */
export function otpSenderFor(mailer: Mailer): SendOtp {
  if (mailer instanceof ConsoleMailer) return consoleOtp;
  return async (input) => {
    if (process.env.NODE_ENV !== 'production') rememberDevOtp(input.email, input.otp);
    await mailer.send(otpMail(input));
  };
}

export function createAuth(env: Env, prisma: PrismaClient, sendOtp: SendOtp = consoleOtp) {
  const googleConfigured = Boolean(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET);

  return betterAuth({
    database: prismaAdapter(prisma, { provider: 'postgresql' }),
    secret: env.AUTH_SECRET,
    baseURL: env.API_URL,
    basePath: '/api/v1/auth',
    trustedOrigins: [env.APP_URL],

    // PRD §12.1.
    advanced: {
      // PRD §0.2: every primary key is a UUID v7, generated by the `uuid_generate_v7()` column
      // default. Better Auth would otherwise insert its own random-string ids, which Postgres
      // rejects on a UUID column ("Error creating UUID, invalid character"). `false` makes the
      // adapter omit `id` on insert so the database default applies.
      database: { generateId: false },
      useSecureCookies: env.NODE_ENV === 'production',
      defaultCookieAttributes: {
        httpOnly: true,
        sameSite: 'lax',
        secure: env.NODE_ENV === 'production',
      },
    },

    session: {
      expiresIn: 60 * 60 * 24 * 30,
      updateAge: 60 * 60 * 24,
    },

    // Role and plan travel on the session so authorisation does not need a second query
    // (PRD §7.2 "role claims").
    user: {
      additionalFields: {
        role: { type: 'string', required: false, defaultValue: 'STUDENT', input: false },
        plan: { type: 'string', required: false, defaultValue: 'FREE_TRIAL', input: false },
        timezone: { type: 'string', required: false, defaultValue: 'Asia/Kolkata', input: false },
      },
    },

    ...(googleConfigured
      ? {
          socialProviders: {
            google: {
              clientId: env.GOOGLE_CLIENT_ID ?? '',
              clientSecret: env.GOOGLE_CLIENT_SECRET ?? '',
            },
          },
        }
      : {}),

    // FR-9.6: an invited address takes its institution seat the first time it signs in. At
    // sign-in rather than at account creation, because a student may already have a free-trial
    // account when their department buys seats. A failure here is logged and swallowed: a seat
    // that did not attach is a support ticket, a sign-in that did not complete is a locked-out
    // student.
    databaseHooks: {
      session: {
        create: {
          async after(session) {
            try {
              const user = await prisma.user.findUnique({
                where: { id: session.userId },
                select: { email: true },
              });
              if (user) await claimInstitutionInvite(prisma, session.userId, user.email);
            } catch (error) {
              // eslint-disable-next-line no-console
              console.error('[auth] could not claim an institution invite', error);
            }
          },
        },
      },
    },

    plugins: [
      emailOTP({
        otpLength: 6,
        expiresIn: 10 * 60,
        async sendVerificationOTP({ email, otp, type }) {
          await sendOtp({ email, otp, type });
        },
      }),
    ],
  });
}

export type Auth = ReturnType<typeof createAuth>;

/** Whether Google sign-in is available, so the web app can hide the button when it is not. */
export function isGoogleConfigured(env: Env): boolean {
  return Boolean(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET);
}
